In [1]:
import pandas as pd
df = pd.read_csv('customer_shopping_behavior.csv')

In [2]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [3]:
df.info

<bound method DataFrame.info of       Customer ID  Age  Gender Item Purchased     Category  \
0               1   55    Male         Blouse     Clothing
1               2   19    Male        Sweater     Clothing
2               3   50    Male          Jeans     Clothing
3               4   21    Male        Sandals     Footwear
4               5   45    Male         Blouse     Clothing
...           ...  ...     ...            ...          ...
3895         3896   40  Female         Hoodie     Clothing
3896         3897   52  Female       Backpack  Accessories
3897         3898   46  Female           Belt  Accessories
3898         3899   44  Female          Shoes     Footwear
3899         3900   52  Female        Handbag  Accessories

      Purchase Amount (USD)       Location Size      Color  Season  \
0                        53       Kentucky    L       Gray  Winter
1                        64          Maine    L     Maroon  Winter
2                        73  Massachusetts    S     Maroon  Spring
3                        90   Rhode Island    M     Maroon  Spring
4                        49         Oregon    M  Turquoise  Spring
...                     ...            ...  ...        ...     ...
3895                     28       Virginia    L  Turquoise  Summer
3896                     49           Iowa    L      White  Spring
3897                     33     New Jersey    L      Green  Spring
3898                     77      Minnesota    S      Brown  Summer
3899                     81     California    M      Beige  Spring

      Review Rating Subscription Status   Shipping Type Discount Applied  \
0               3.1                 Yes         Express              Yes
1               3.1                 Yes         Express              Yes
2               3.1                 Yes   Free Shipping              Yes
3               3.5                 Yes    Next Day Air              Yes
4               2.7                 Yes   Free Shipping              Yes
...             ...                 ...             ...              ...
3895            4.2                  No  2-Day Shipping               No
3896            4.5                  No    Store Pickup               No
3897            2.9                  No        Standard               No
3898            3.8                  No         Express               No
3899            3.1                  No    Store Pickup               No

     Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0                Yes                  14          Venmo            Fortnightly
1                Yes                   2           Cash            Fortnightly
2                Yes                  23    Credit Card                 Weekly
3                Yes                  49         PayPal                 Weekly
4                Yes                  31         PayPal               Annually
...              ...                 ...            ...                    ...
3895              No                  32          Venmo                 Weekly
3896              No                  41  Bank Transfer              Bi-Weekly
3897              No                  24          Venmo              Quarterly
3898              No                  24          Venmo                 Weekly
3899              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]>

In [4]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [5]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [6]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [7]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [8]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ','_')

In [9]:
df.isnull().sum()

customer_id               0
age                       0
gender                    0
item_purchased            0
category                  0
purchase_amount_(usd)     0
location                  0
size                      0
color                     0
season                    0
review_rating             0
subscription_status       0
shipping_type             0
discount_applied          0
promo_code_used           0
previous_purchases        0
payment_method            0
frequency_of_purchases    0
dtype: int64

In [10]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [11]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [12]:
bins = [18, 25, 40, 60, float('inf')]
labels = ['young_adults', 'adults', 'middle_age', 'senior']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels, right=False)

In [13]:
df[['age','age_group']].head(10)

   age     age_group
0   55    middle_age
1   19  young_adults
2   50    middle_age
3   21  young_adults
4   45    middle_age
5   46    middle_age
6   63        senior
7   27        adults
8   26        adults
9   57    middle_age

In [14]:
frequency_mapping = {
    'Daily': 1,
    'Weekly': 7,
    'Bi-Weekly': 14,
    'Fortnightly': 14,
    'Monthly': 30,
    'Quarterly': 90,
    'Every 3 Months': 90,
    'Bi-Quarterly': 180,
    'Annually': 365
}

df['purchase_frequency_days'] = (df['frequency_of_purchases'].str.strip().map(frequency_mapping))

In [15]:
df[['frequency_of_purchases','purchase_frequency_days']].head(10)

  frequency_of_purchases  purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [16]:
df[['discount_applied', 'promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [17]:
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [18]:
df=df.drop('promo_code_used' , axis=1)

In [19]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='object')

In [20]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\teert\anaconda3\lib\site-packages (2.9.11)
Requirement already satisfied: sqlalchemy in c:\users\teert\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\teert\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\teert\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [21]:
pip install pymysql

Requirement already satisfied: pymysql in c:\users\teert\anaconda3\lib\site-packages (1.1.2)
Note: you may need to restart the kernel to use updated packages.

In [22]:
from sqlalchemy import create_engine

In [23]:
username = "root"
password = "Password"
host = "localhost"
port = "3306"
database = "customer_behavior"

engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/{database}?charset=utf8mb4"
)

In [24]:
engine.connect()

In [25]:
# Step 2: Load DataFrame into MySQL
table_name = "customer"  # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)

3900